---
title: Eva De Geyter
timezone: UTC
collections:
  clients:
    title: Clients
    output: false
  experience:
    title: Experience
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  sections:
    title: Sections
    output: false
  services:
    title: Services
    output: false
  skills:
    title: Skills
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    client: 
    skills: 
    images: 
    cover_photo: "/assets/images/default_project_cover.jpg"
- scope:
    path: ''
    type: skills
  values:
    icon: 
- scope:
    path: ''
    type: experience
  values:
    period: 
    type:
      werk: false
      opleiding: false
- scope:
    path: ''
    type: services
  values:
    icon: 
- scope:
    path: ''
    type: clients
  values:
    link: 
    logo: 
- scope:
    path: ''
    type: sections
  values:
    background_color: 
    background_image: 
    is_dark_background: 
    is_fullscreen: 
    layout: section
    lists:
      projects: false
      skills: false
      experience: false
      services: false
      clients: false
- scope:
    path: ''
    type: pages
  values:
    sections: 
logo_title: 
email: hallo@evadegeyter.be
description: 'Eva De Geyter is freelance copywriter & content en communicatie consultant

'
background_image: "/uploads/bureaublad-6.jpg"
baseurl: 
url: https://evadegeyter.be
fonts:
  import_url: https://fonts.googleapis.com/css?family=Amatic+SC|Quicksand
  main_font_family: Quicksand
  paragraph_font_family: Quicksand
social:
- network: pinterest
  username: poppinette
markdown: kramdown
exclude:
- package.json
- node_modules
- gulpfile.js
sass:
  style: compressed
colours:
  theme_one: "#e5f5f5"
  theme_two: "#f7d3c8"
  theme_three: "#1422ae"
