---
title: Eva De Geyter
timezone: UTC
collections:
  clients:
    title: Clients
    output: false
  experience:
    title: Experience
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  sections:
    title: Sections
    output: false
  services:
    title: Services
    output: false
  skills:
    title: Skills
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: default.project
    client: 
    skills: 
    images: 
    cover_photo: "/assets/images/default_project_cover.jpg"
- scope:
    path: ''
    type: skills
  values:
    icon: 
- scope:
    path: ''
    type: experience
  values:
    period: 
    type:
      werk: false
      opleiding: false
- scope:
    path: ''
    type: services
  values:
    icon: 
- scope:
    path: ''
    type: clients
  values:
    link: 
    logo: 
- scope:
    path: ''
    type: sections
  values:
    background_color: 
    layout: section
    lists:
      projects: false
      skills: false
      experience: false
      services: false
      clients: false
- scope:
    path: ''
    type: pages
  values:
    sections: 
logo_title: Eva
email: hallo@evadegeyter.be
description: 'Eva De Geyter is freelance copywriter, journaliste en creatieve duizendpoot

'
background_image: "/assets/images/b1.jpg"
baseurl: ''
url: https://evadegeyter.be
social:
- network: pinterest
  username: poppinette
- network: instagram
  username: evadegeyter
markdown: kramdown
exclude:
- package.json
- node_modules
- gulpfile.js
