---
title: Eva De Geyter
timezone: UTC
collections:
  clients:
    title: Clients
    output: false
  experience:
    title: Experience
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  services:
    title: Services
    output: false
  skills:
    title: Skills
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    client: 
    skills: 
    project_images: 
- scope:
    path: ''
    type: skills
  values:
    icon: 
- scope:
    path: ''
    type: experience
  values:
    period: 
- scope:
    path: ''
    type: services
  values:
    icon: 
- scope:
    path: ''
    type: clients
  values:
    link: 
    logo: 
logo_title: Eva
email: hallo@evadegeyter.be
description: 'Eva De Geyter is freelance copywriter, journaliste en creatieve duizendpoot

'
background_image: "/assets/images/b1.jpg"
baseurl: ''
url: http://evadegeyter.dev
social:
- network: facebook
  username: poppinette
- network: instagram
  username: evadegeyter
markdown: kramdown
